#ifndef GAME_RULE_H
# define GAME_RULE_H

# define WIDTH 500//1280
# define HEIGHT 500//768
# define MAP_WIDTH 50
# define MAP_HEIGHT 50
# define MAP_MARGING 3
# define NB_MAX_COLLECTIBLE (MAP_WIDTH - MAP_MARGING * 2) * (MAP_HEIGHT - MAP_MARGING * 2) * 0.05
# define NB_MIN_COLLECTIBLE (MAP_WIDTH - MAP_MARGING * 2) * (MAP_HEIGHT - MAP_MARGING * 2) * 0.01
# define TILE_SIZE 10//32


#endif